name             'nginx'
maintainer       'Jimmy Malone'
maintainer_email 'jimmy@girlfriend.com'
license          'All rights reserved'
description      'Installs/Configures nginx for girlfriend'
long_description 'Installs/Configures nginx for girlfriend'
version          '0.1.0'
